# Generated by Django 3.2.6 on 2021-09-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210919_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogy',
            new_name='Category',
        ),
    ]
