# Generated by Django 3.2.6 on 2022-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=5, upload_to='blog/images'),
            preserve_default=False,
        ),
    ]
